# Generated by Django 5.1.1 on 2025-02-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionattempt',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='userquestionattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userquestionattempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestionattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='UserQuestionAttempt',
        ),
    ]
