# Generated by Django 5.0.1 on 2025-01-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic_lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='module',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
