# Generated by Django 5.0.1 on 2025-01-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='completed_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='current_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
