# Generated by Django 5.2.7 on 2025-11-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabic_lessons', '0003_alter_userprogress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty_level',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
